workspacePath : /home/sandeep/projects/workspace/web_automation
enableHeadless : false
enableServerCommunication : true
configProperties :
   capitalystServer : localhost:8080

siteAutomatorConfigs :
   - siteId : ICICIBank
     enabled : false
     className : com.sandy.automator.icicibank.ICICIBankSiteAutomator
     useCaseAutomatorConfigs :
        - ucId : CCEntryParser
          className : com.sandy.automator.icicibank.cc.CCEntryParseUCAutomator
          
   - siteId : ICICIDirect
     enabled : true
     className : com.sandy.automator.icicidirect.ICICIDirectSiteAutomator
     useCaseAutomatorConfigs :
        - ucId : MFPortfolioAutomator
          enabled : false
          className : com.sandy.automator.icicidirect.mf.MFPortfolioUseCaseAutomator
        - ucId : EquityPortfolioAutomator
          className : com.sandy.automator.icicidirect.equity.EquityPortfolioUseCaseAutomator
          
   - siteId : MorningStar
     enabled : false
     useCaseAutomatorConfigs :
        - ucId : MFEnrich
          className : com.sandy.automator.morningstar.MFMasterDataImportUCAutomator
             