workspacePath : /home/sandeep/projects/workspace/web_automation
enableHeadless : false
enableServerCommunication : true
configProperties :
   capitalystServer : 192.168.0.116:8080

siteAutomatorConfigs :
   - siteId : ICICIDirect
     className : com.sandy.automator.icicidirect.ICICIDirectSiteAutomator
     useCaseAutomatorConfigs :
        - ucId : MFPortfolioAutomator
          className : com.sandy.automator.icicidirect.mf.MFPortfolioUseCaseAutomator
   - siteId : MorningStar
     enabled : false
     useCaseAutomatorConfigs :
        - ucId : MFEnrich
          className : com.sandy.automator.morningstar.MFMasterDataImportUCAutomator
             