workspacePath : /home/sandeep/projects/workspace/web_automation
enableHeadless : true
enableServerCommunication : true
configProperties :
   propKeyA : String

siteAutomatorConfigs :
   - siteId : ICICIDirect
     className : com.sandy.automator.icicidirect.ICICIDirectSiteAutomator
     configProperties :
        propKeyA : propValueSiteConfig
     useCaseAutomatorConfigs :
        - className : com.sandy.automator.icicidirect.MFPortfolioUseCaseAutomator
          configProperties :
             propKeyA : propValueUCConfig
             property : ${propKeyA}
             stringProp : Hello
             booleanProp : false
             