workspacePath : /home/sandeep/projects/workspace/web_automation
enableHeadless : false
enableServerCommunication : true
configProperties :
   capitalystServer : 192.168.0.116:8080
   #capitalystServer : 127.0.0.1:8080

siteAutomatorConfigs :
   - siteId : ICICIBank
     enabled : true
     className : com.sandy.automator.icicibank.ICICIBankSiteAutomator
     useCaseAutomatorConfigs :
        - ucId : CCEntryParser
          className : com.sandy.automator.icicibank.cc.CCTxnScrapeAutomator
          
   - siteId : ICICIDirect
     enabled : false
     className : com.sandy.automator.icicidirect.newsite.ICICIDirectNewSiteAutomator
     useCaseAutomatorConfigs :
        - ucId : EquityPortfolioAutomator
          enabled : true
          className : com.sandy.automator.icicidirect.newsite.equity.EquityPortfolioUseCaseAutomator
        - ucId : MFPortfolioAutomator
          enabled : false
          className : com.sandy.automator.icicidirect.newsite.mf.MFPortfolioUseCaseAutomator
          
   - siteId : MorningStar
     enabled : false
     useCaseAutomatorConfigs :
        - ucId : MFEnrich
          className : com.sandy.automator.morningstar.MFMasterDataImportUCAutomator

   
             