workspacePath : /home/sandeep/projects/workspace/web_automation
enableHeadless : false
enableServerCommunication : true
configProperties :
   capitalystServer : 127.0.0.1:8080

siteAutomatorConfigs :
   - siteId : ETrade
     enabled : false
     className : com.sandy.automator.etrade.ETradeSiteAutomator
     useCaseAutomatorConfigs :
        - ucId : HoldingsProcessor
          className : com.sandy.automator.etrade.holding.HoldingsParseAndUploadUCAutomator
          
   - siteId : ICICIBank
     enabled : false
     className : com.sandy.automator.icicibank.ICICIBankSiteAutomator
     useCaseAutomatorConfigs :
        - ucId : CCEntryParser
          className : com.sandy.automator.icicibank.cc.CCTxnScrapeAutomator
          
   - siteId : ICICIDirect
     enabled : false
     className : com.sandy.automator.icicidirect.ICICIDirectSiteAutomator
     useCaseAutomatorConfigs :
        - ucId : MFPortfolioAutomator
          enabled : true
          className : com.sandy.automator.icicidirect.mf.MFPortfolioUseCaseAutomator
        - ucId : EquityPortfolioAutomator
          enabled : true
          className : com.sandy.automator.icicidirect.equity.EquityPortfolioUseCaseAutomator
          
   - siteId : MorningStar
     enabled : false
     useCaseAutomatorConfigs :
        - ucId : MFEnrich
          className : com.sandy.automator.morningstar.MFMasterDataImportUCAutomator

   
             